version: "3"
services:
  postgresql:
    image: postgres
    restart: always
    container_name: local-postgres
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=workshop-5"
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - 15432:5432
  redis:
    image: redis
    restart: always
    container_name: local-redis
    ports:
      - 16379:6379
